# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180522_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoingonTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=-99, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='main.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goingontrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='main.Trip'),
        ),
        migrations.AddField(
            model_name='goingontrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.User'),
        ),
    ]
